In [1]:
import torch
import numpy as np

In [3]:
x1 = torch.Tensor(np.ones([2,4])*2)
x2 = torch.Tensor(np.ones([2,4])*3)

print(x1)
print(x2)


tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [5]:
x3 = torch.cat([x1, x2], dim=-1)
print(x3)
print(x3.shape)

tensor([[2., 2., 2., 2., 3., 3., 3., 3.],
        [2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([2, 8])


In [6]:
x4 = torch.reshape(x3, [-1, int(x3.shape[-1]/2)])
print(x4)
print(x4.shape)

tensor([[2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])
torch.Size([4, 4])


In [8]:
a = ["11", "22", "44"]

b = a[:2]
b


['11', '22']